name: 'Main Action'
description: 'This is the main action'
branding:
  icon: arrow-up-right
  color: orange
inputs:
  GITHUB_TOKEN:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
  ACTION:
    description: 'Which action to take'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
