name: check-run-all-test
on: check_run
    
jobs:
  check-run-test:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
    - name: Show Information
      run: |
        echo "Name is ${{ github.event.inputs.name }} "
        echo "This workflow run is triggered by ${{ github.event_name }} "
        echo " *****************************************************************************"
        echo "$GITHUB_CONTEXT"
        echo " *****************************************************************************"
    - name: Try to fail
      run: exit 1