name: check-run-created-test
on:
  check_run:
    types: [created]

# TODO verify it is the expected check-run, since this event is probably triggered for all check-runs
jobs:
  check-run-test:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
      EVENT_CONTEXT: ${{ toJson(github.event) }}
    steps:
    - name: Show Information
      run: |
        echo "This workflow run is triggered by ${{ github.event_name }} "
        echo " *****************************************************************************"
        echo "$GITHUB_CONTEXT"
        echo " *****************************************************************************"
    - uses: actions/checkout@v2
      with:
        ref: "${{ github.event.check_run.head_sha }}"
    - id: auth
      uses: jnwng/github-app-installation-token-action@v1
      with:
        appId: ${{ secrets.APP_ID }}
        installationId: ${{ secrets.APP_INSTALLATION_ID }}
        privateKey: ${{ secrets.APP_PRIVATE_KEY }}
    - id: codeowners_check
      name: codeowners_check
      uses: ./.github/actions/action
      with:
        githubToken: ${{ steps.auth.outputs.token }}
        action: "CHECK_CODEOWNERS"