name: codeowners-generate-auto-check
on: push
    
jobs:
  trigger-codeowners-generate-auto:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
    - name: Show Information
      run: |
        echo "This workflow run is triggered by ${{ github.event_name }} ."
        echo " *****************************************************************************"
        echo "$GITHUB_CONTEXT"
        echo " *****************************************************************************"
    - name: Hello world
      run: |
        echo Hello world $FIRST_NAME $middle_name $Last_Name!
        echo "Hello ${{ github.event_name }}!"
      env:
        FIRST_NAME: Mona
        middle_name: The
        Last_Name: Octocat
    - uses: actions/checkout@v1
    - id: auth
      uses: jnwng/github-app-installation-token-action@v1
      with:
        appId: ${{ secrets.APP_ID }}
        installationId: ${{ secrets.INSTALLATION_ID }}
        privateKey: ${{ secrets.PRIVATE_KEY }} 
    - id: codeowners_check
      name: codeowners_check
      run: |
        echo "Starting..."
        curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer ${{ steps.auth.outputs.token }}" \
        https://api.github.com/repos/${{ github.repository }}/check-runs \
        -d '{
                "name": "Check Codeowners",
                "head_sha": "${{ github.sha }}",
                "status": "in_progress",
                "actions": [{
                  "label": "Button text",
                  "description": "Some description",
                  "identifier": "robs-action"
                  }]
            }'
    - name: Print2
      run: echo "${{ toJson(steps.codeowners_check.outputs) }}"
    - name: Print
      run: echo "${{ steps.codeowners_check.outputs.isValid }}"
    - name: IsValid
      if: steps.codeowners_check.outputs.isValid == 'false'
      run: exit 1