name: codeowners-generate-auto-check
on: push
    
jobs:
  codeowners-generate-auto-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
    - name: Show Information
      run: |
        echo "This workflow run is triggered by ${{ github.event_name }} ."
        echo " *****************************************************************************"
        echo "$GITHUB_CONTEXT"
        echo " *****************************************************************************"
    - uses: actions/checkout@v2
    - id: auth
      uses: jnwng/github-app-installation-token-action@v1
      with:
        appId: ${{ secrets.APP_ID }}
        installationId: ${{ secrets.APP_INSTALLATION_ID }}
        privateKey: ${{ secrets.APP_PRIVATE_KEY }}
    - id: codeowners_start
      name: codeowners_start
      uses: ./.github/actions/action
      if: github.event_name == 'push'
      with:
        action: "START"