name: Codeowners Generator > build test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  herald:
    name: Run Codeowners Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install packages
        run: npm install
      - name: Dry run Codeowners Generator with checked in dist/
        id: codeowners-dist
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTION: 'START'
      - name: Rebuild binary
        run: npm run build
      - name: Dry run Herald rules with rebuilt dist/
        id: codeowners-rebuilt
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTION: 'CHECK_CODEOWNERS'
